default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  <% if !ENV['DATABASE_URL'] %>
  database: hos_development
  <% end %>

test:
  <<: *default
  database: hos_test
  <% if ENV['GITHUB_ACTIONS'] == 'true' %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  <% end %>

production:
  <<: *default
